services:
  pgdatabase:
    image: pgvector/pgvector:pg17
    env_file: .env
    volumes:
      - "pgvector_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8085:80"

volumes:
  pgvector_data:
  pgadmin_data: