[project]
name = "wikifin-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bastien Winant", email = "armand.winant@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
wikifin-rag = "wikifin_rag:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
