[project]
name = "wikifin-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bastien Winant", email = "armand.winant@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "hyperopt>=0.3.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "onnxruntime>=1.29.0",
    "openai>=3.10.0",
    "python-dotenv>=1.2.3",
    "scrapy>=2.18.0",
    "seaborn>=0.13.2",
    "sqlitesearch>=0.3.0",
    "streamlit>=1.63.0",
    "tokenizers>=0.23.2",
    "tqdm>=4.70.0",
    "trafilatura>=2.2.0",
]

[project.scripts]
wikifin-rag = "wikifin_rag:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "huggingface-hub>=1.30.0",
    "jupyter>=1.1.1",
]
